### ISSUE TITLE
Script not deploying js folder from dist

### ISSUE THREAD

**Issue by GhostInTheMachines** [maciejkorsan/frontendkickstarter#1]
Everything seems to work except for the js/ directory being left behind for some reason.

## My Setup
OS: Windows 10
Node version: v8.10.0
NPM version: 5.6.0
Installed plugins:
`-- ftp-deploy@1.2.2
  +-- async@2.6.0
  | `-- lodash@4.17.5
  +-- jsftp@2.0.0
  | +-- debug@2.6.9
  | | `-- ms@2.0.0
  | +-- ftp-response-parser@1.0.1
  | | `-- readable-stream@1.1.14
  | |   +-- core-util-is@1.0.2
  | |   +-- inherits@2.0.3
  | |   +-- isarray@0.0.1
  | |   `-- string_decoder@0.10.31
  | +-- once@1.4.0
  | | `-- wrappy@1.0.2
  | +-- parse-listing@1.1.3
  | +-- stream-combiner@0.2.2
  | | +-- duplexer@0.1.1
  | | `-- through@2.3.8
  | `-- unorm@1.4.1
  +-- minimatch@3.0.4
  | `-- brace-expansion@1.1.11
  |   +-- balanced-match@1.0.0
  |   `-- concat-map@0.0.1
  `-- read@1.0.7
    `-- mute-stream@0.0.7
## Steps to reproduce
1. clone the repo
2. npm install modules for my project (bootstrap, mdbootstrap, jquery)
3. Copy my html code into content/ and partial/ directories
4. npm install and gulp commands
5. Create my repo on GitHub
6. Setup and push code to origin
7. Link CircleCI to the project.
8. Setup FTP env on CircleCI
9. Edit and push again

## Results
+ CircleCI builds successfully
+ assets/, css/ and index.html are created on remote server with all files inside

## Issues
+ No js/ directory

## Troubleshooting
+ checked dist/js locally which has all of my .js files built from npm plugins

**Comment by maciejkorsan** [comment]
Can you show me your package.json?

**Comment by GhostInTheMachines** [comment]
Sure thing, here it is.

{
  "name": "island-boy-charters",
  "description": "base code and packages for IBC",
  "version": "1.0.0",
  "repository": {
    "type": "git",
    "url": "git@github.com:kimbletech/islandboycharters.com.git"
  },
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "browser-sync": "^2.23.5",
    "browserify": "^2.4.0",
    "ftp-deploy": "^1.2.2",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^4.1.0",
    "gulp-babel": "^6.1.2",
    "gulp-browserify": "^0.5.1",
    "gulp-headerfooter": "^1.0.3",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-tinypng-compress": "^1.2.1",
    "gulp-uglify": "^3.0.0"
  },
  "dependencies": {
    "bootstrap": "^4.0.0",
    "jquery": "^1.9.1",
    "mdbootstrap": "^4.5.0",
    "popper.js": "^1.12.9"
  }
}

**Comment by maciejkorsan** [comment]
https://github.com/kimbletech/islandboycharters.com if this is your repository, there is no js directory in app, please check if you've added it to the repository correctly :)

**Comment by GhostInTheMachines** [comment]
I must have made an incorrect assumption here.  I thought that the code was being deployed from the dist/ directory.

I might have moved the js files to the dist/ directory manually when I was testing this. What I was trying to do, was to have the js and bootstrap files served from the installed node_modules.

**Comment by maciejkorsan** [comment]
dist directory is created by `gulp build` command on circleci, you
shouldn't place your files manually in the dist directory :)

--

Maciej Korsan {••}

korsan.pl / maciejkorsan.com
+ 48 *505 172 249*



2018-03-30 12:17 GMT+02:00 Dennis Kimble <notifications@github.com>:

**Comment by GhostInTheMachines** [comment]
Yep, looks like I have the process down now.  Thanks!
